const ActionType = { 
    ADD_MENU : "ADD_MENU",
    ADD_TABLE : "ADD_TABLE",
    ADD_CUSTOMER:"ADD_CUSTOMER",
    DELETE_MENU : "DELETE_MENU",
    DELETE_TABLE : "DELETE_TABLE",
    DELETE_CUSTOMER:"DELETE_CUSTOMER",
    MOVE_CUSTOMER:"MOVE_CUSTOMER",
    MOVE_MENU:"MOVE_MENU",
    MOVE_TABLE:"MOVE_TABLE",
    MOVE_HOME:"MOVE_HOME",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    OPEN_FORM:"OPEN_FORM",
    CLOSE_FORM:"CLOSE_FORM"
}

//you can put this as constants like this

export default ActionType;